# goal is to check code synatx, indentaion whenever someone pushes the code
name: Lint

on:
  push:
    paths: "*.py"
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/clone
        uses: actions/checkout@v7
      - name: Install lint Ruff
        run: pip install ruff
      - name: Ruff Fix
        run: ruff check --fix
      - name: Check Ruff
        run: ruff check .
      
